In [7]:
# to work with phonemes: http://www.nltk.org/_modules/nltk/corpus/reader/cmudict.html
# from nltk.corpus import brown
# from nltk.corpus import cmudict
import nltk
nltk.download()

showing info http://www.nltk.org/nltk_data/


True

In [15]:
def read_examples(filepath):
    examples = []
    with open(filepath, "r") as f:
        for line in f:
            for word in line.split():
                examples.append(word)
    return examples

In [14]:
import nltk
from utils import random_idx
# http://www.nltk.org/_modules/nltk/corpus/reader/cmudict.html
# assign every phoneme to a feature vector
k = 500
N = 1000
NUM_CLASSES = 2 # 0 for non-ed verb, 1 for ed verb
phonemes = ["AA", "AE", "AH", "AO", "AW", "AY", "B", "CH", "D", "DH", "EH", "ER", "EY", "F", "G", "HH", "IH",
            "IY", "JH", "K", "L", "M", "N", "NG", "OW", "OY", "P", "R", "S", "SH", "T", "TH", "UH", "UW", "V", "W",
            "Y", "Z", "ZH"
           ]
RI_phonemes = random_idx.generate_phoneme_id_vectors(N, k, phonemes)

[[u'B', u'AA1', u'R', u'B', u'AH0', u'L', u'Z']]
[[u'B', u'AA1', u'R', u'B', u'IH0', u'K', u'Y', u'UW2']]
[[u'B', u'AA1', u'R', u'B', u'IH0', u'K', u'Y', u'UW2', u'D']]
[[u'B', u'AA1', u'R', u'B', u'IH0', u'K', u'Y', u'UW2', u'IH0', u'NG']]
[[u'B', u'AA1', u'R', u'B', u'IH0', u'K', u'Y', u'UW2', u'Z']]


In [17]:
# first association is between ed verbs and their present tense
nonedpast = read_examples("wickle_train/noned_past_example.txt")
edpast = read_examples("wickle_train/ed1000.txt")
past = nonedpast + edpast
ytrain = np.ones(len(past))
ytrain[:len(nonedpast)]  = 0
# to be generated
Xtrain = np.zeros((len(past), N))

In [18]:
# encode verbs as phonemes, then 
arpabet = nltk.corpus.cmudict.dict()
for word in (past):
    # need to fix key errors.
    print(arpabet[word])
    
# make the test set the brown corpus

[[u'W', u'AA1', u'Z'], [u'W', u'AH1', u'Z'], [u'W', u'AH0', u'Z'], [u'W', u'AO1', u'Z']]
[[u'W', u'ER0'], [u'W', u'ER1']]
[[u'B', u'IH1', u'N'], [u'B', u'AH0', u'N'], [u'B', u'IH0', u'N']]
[[u'ER0', u'OW1', u'Z']]
[[u'AH0', u'W', u'OW1', u'K']]
[[u'W', u'AA1', u'Z'], [u'W', u'AH1', u'Z'], [u'W', u'AH0', u'Z'], [u'W', u'AO1', u'Z']]
[[u'B', u'AO1', u'R']]
[[u'B', u'AO1', u'R', u'N']]
[[u'B', u'EY1', u'D']]
[[u'B', u'IY1', u'T']]
[[u'B', u'IY1', u'T', u'AH0', u'N']]
[[u'B', u'IH0', u'K', u'EY1', u'M'], [u'B', u'IY0', u'K', u'EY1', u'M']]
[[u'B', u'IH0', u'K', u'AH1', u'M']]
[[u'B', u'IH0', u'G', u'AE1', u'N'], [u'B', u'IY0', u'G', u'AE1', u'N']]
[[u'B', u'IY0', u'G', u'AO1', u'T']]
[[u'B', u'IH0', u'G', u'AH1', u'N'], [u'B', u'EY1', u'G', u'AH0', u'N']]
[[u'B', u'EH1', u'N', u'T']]
[[u'B', u'EH1', u'T']]
[[u'B', u'IH1', u'T']]
[[u'B', u'IH1', u'T', u'AH0', u'N']]
[[u'B', u'L', u'EH1', u'D']]
[[u'B', u'L', u'UW1']]
[[u'B', u'L', u'OW1', u'N']]
[[u'B', u'OW1', u'D']]
[[u'B', u'R', u'EH1', 

KeyError: 'clove'

In [ ]:
"""
Preprocessing:
DONE: phonetic encoding of verbs based on cmu dictionary
TO DO: categorize verbs based on their frequency (just low, medium, or high)

Pentti:
These are my notes on learning the past tense of
English verbs ("Chapter18.pdf" of Rumelhart &
McClelland 1986) from the meeting on Friday.  We'll
learn their model and the Perceptron Learning Rule
by reproducing the work in sections "Learning" and
"Learning Regular and Exceptional Patterns in a Pattern
Associator" (pp. 225-233).  It's a simple exercise with
artificial data.  Here's what I'd like you to do:

1. First see how Figure 3 corresponds to having learned
   one of the association (one input-output pair).

2. Then start with an 8 x 8 matrix of 0s and train it
   for that same association using the perceptron-
   learning rule, to get a matrix that looks like Table
   1A.  Because training is stochastic, the numbers you
   get will not be exactly the same.

3. Do the same with the other association (Table 2B).

4. Then reproduce Table 2C.  Now we are learning two
   associations.

5. Figure out what they mean by "Rule of 78" and see if
   you can reproduce the equivalent of Table 2D.

6. Finally, see if you can reproduce all four stages
   shown in Table 4.

I'd like to see all 8 matrices you get, all that
correspond to those sown in Tables 2 and 4.
"""

In [5]:
# https://blog.dbrgn.ch/2013/3/26/perceptrons-in-python/
import numpy as np
from random import choice
from numpy import array, dot, random

unit_step = lambda x: 0 if x < 0 else 1

training_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]

w = random.rand(3)
errors = []
eta = 0.2
n = 100

for i in xrange(n):
    x, y = choice(training_data)
    yHat = dot(w, x)
    error = y - unit_step(result)
    errors.append(error)
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))

[0 0]: -5.44855538562 -> 0
[0 1]: -5.18683850822 -> 0
[1 0]: -5.16465588571 -> 0
[1 1]: -4.90293900831 -> 0


In [ ]:
# http://sebastianraschka.com/Articles/2015_singlelayer_neurons.html
# does not guarantee large/good margin.
import numpy as np

class Perceptron(object):

    def __init__(self, eta=0.01, epochs=50):
        self.eta = eta
        self.epochs = epochs

    def train(self, X, y):

        self.w_ = np.zeros(1 + X.shape[1])
        self.errors_ = []

        for _ in range(self.epochs):
            errors = 0
            for xi, target in zip(X, y):
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] +=  update * xi
                self.w_[0] +=  update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self

    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def predict(self, X):
        return np.where(self.net_input(X) >= 0.0, 1, -1)
