In [1]:
import numpy as np
from sklearn.decomposition import IncrementalPCA

In [15]:
mu, sigma = 0, 0.1 # mean and standard deviation
A = np.random.normal(mu, sigma, (3,2))
print "A"
u, s, v = np.linalg.svd(A)
print (u.shape, s.shape, v.shape)
print u
print s
print v

newrow = np.random.normal(mu, sigma, 2)
Aprime = np.vstack((A, newrow))
print "Aprime"
u, s, v = np.linalg.svd(Aprime)
print(u.shape, s.shape, v.shape)
print u
print s
print v

A
((3, 3), (2,), (2, 2))
[[-0.26216515  0.34789293  0.90013329]
 [-0.11536183 -0.93736771  0.32868437]
 [ 0.95810286 -0.01767143  0.28587871]]
[ 0.23449579  0.23325198]
[[-0.23820378 -0.9712152 ]
 [ 0.9712152  -0.23820378]]
Aprime
((4, 4), (2,), (2, 2))
[[-0.40548394  0.03675054  0.8214416   0.39933178]
 [ 0.57721926 -0.71116075  0.37979784 -0.12969932]
 [ 0.61308045  0.70193071  0.33663516 -0.1345452 ]
 [ 0.35571486 -0.01389472 -0.26012319  0.89755769]]
[ 0.25017216  0.23396246]
[[-0.88120577 -0.4727329 ]
 [ 0.4727329  -0.88120577]]


In [20]:
#V = A.TA
#U = AA.T

ipca = IncrementalPCA(n_components=2, batch_size=4)
ipca.fit(Aprime.T.dot(Aprime))
V = ipca.transform(Aprime.T.dot(Aprime))


ipca = IncrementalPCA(n_components=4, batch_size=4)
ipca.fit(Aprime.dot(Aprime.T))
U = ipca.transform(Aprime.dot(Aprime.T))

print (U.shape, U)
print (V.shape, V)

((4, 4), array([[ -3.45036790e-03,  -4.31237120e-02,  -1.73472348e-18,
          3.46944695e-18],
       [  3.97744728e-02,   1.67957684e-02,   1.73472348e-18,
          0.00000000e+00],
       [ -3.74366994e-02,   2.19492433e-02,   1.73472348e-18,
          1.73472348e-18],
       [  1.11259448e-03,   4.37870026e-03,   1.08420217e-18,
          1.08420217e-19]]))
((2, 2), array([[  3.91988995e-02,   6.77746870e-18],
       [ -3.91988995e-02,  -9.32489280e-18]]))


In [ ]:
"""
Did not work for now. so sad

incremental svd. our version of incremental svd seems to be different bc it’s not just addition. sounds lik eadding an extra row.
https://core.ac.uk/download/pdf/287126.pdf
https://github.com/andrewssobral/imtsl/blob/master/libs/IncPACK2/seqkl.m
http://www.stat.osu.edu/~dmsl/thinSVDtracking.pdf
https://stats.stackexchange.com/questions/177007/updating-svd-decomposition-after-adding-one-new-row-to-the-matrix

so my plan was to fix incremental pca. where you take the pca of A, A^T. bc svd is from A^TA, AA^T


https://github.com/jbencook/am205
https://github.com/aaw/IncrementalSVD.jl
http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.IncrementalPCA.html
https://stats.stackexchange.com/questions/134282/relationship-between-svd-and-pca-how-to-use-svd-to-perform-pca
https://scicomp.stackexchange.com/questions/2678/updatable-svd-implementation-in-python-c-or-fortran

A^TA => V
AA^T => U
"""